### ISSUE TITLE
City Index Page 3: Wireframe Implementation

### ISSUE THREAD

**Issue by ldhandley** [thoughtstem/metacoders-dot-org#32]

**Comment by ldhandley** [comment]
Wireframe to implement: https://drive.google.com/file/d/1-hV3Nxx7tcABi99YeAHt_rf6FxHAlfc4/view?usp=sharing. See Issue #31 for more details.

**Comment by ldhandley** [comment]
The wireframe for the "Course info" modal on the summer camp table is here: https://drive.google.com/file/d/1846JwqXdUbAF8wdHoGqEAG78sAtLI2VI/view?usp=sharing.

**Comment by aBlender** [comment]
Closing this because course registration is functional and live.

Camp calendar still needs implementation (but I think it should go in a new milestone).
