### ISSUE TITLE
Register a Location 3: Implement Wireframe

### ISSUE THREAD

**Issue by ldhandley** [thoughtstem/metacoders-dot-org#40]

**Comment by aBlender** [comment]
Updated the partners page according to this doc:

https://docs.google.com/document/d/18tDf-ZNT77RqfuBNkTNTUamU0Si_sVy3cKwsS9pVW54/edit

Some of it still looks a bit plain. It could use some section titles and the jumbotron subtitle should be replaced with shorter tag line to match the rest of the website. Also, the bold words in the paragraph may be a bit too much.
