### ISSUE TITLE
Put "Coming Soon" on city-specific pages where we don't have classes scheduled yet (pretty much all of them!)

### ISSUE THREAD

**Issue by ldhandley** [thoughtstem/metacoders-dot-org#59]

**Comment by ldhandley** [comment]
Until we have classes scheduled, city-specific pages should say we're coming soon. We should also make a waitlist (Google form) so that we can contact people when we get classes online.

**Comment by aBlender** [comment]
@ldhandley The Coming Soon part is done. Is there a google form or did you want this to be similar to the course waitlist mailto: link?

**Comment by aBlender** [comment]
I created a city page form and added a prefilled link (with the city name) in each "Coming Soon" section.

Prefilled link example:
https://docs.google.com/forms/d/e/1FAIpQLSfS5L8lP3vLUYhMi7lB5l6ikv4_ZOhejPVf8yjk9uuSiolRIA/viewform?usp=pp_url&entry.162480533=Minneapolis

Form:
https://docs.google.com/forms/d/1wSLumdVvwRr46ym9QZaRq9cIgdWO9MnK69Icg01wJCo/edit

At the moment, it uses the exact city-name from each city page as the prefill data. It might be a good idea to add the **state abbreviation** as well. It would then also match the city cards from the city search page.
