### ISSUE TITLE
Don't link to images for city banners; put images for cities in repo

### ISSUE THREAD

**Issue by ldhandley** [thoughtstem/metacoders-dot-org#73]
Banner images should be 2000 pixels wide max
Banner images should be "saved for web" on Photoshop

**Comment by aBlender** [comment]
Done and pushed to dev.

I used the Save For Web (via RIOT plugin) option in irfanview. Resized width to 2000, keep aspect, default re-sample setting, and progressive enabled. For the jpeg compression, I used 60% if there were a lot of details and up 80% if there were a lot of smooth gradients (compression is very noticeable in these cases). Each file was less than 500KB (most less then 400KB).

**Comment by ldhandley** [comment]
Awesome! Thanks, Jason!
